CmsShoppingCart/Controllers/PagesController.cs
using CmsShoppingCart.Infrastructure;
using CmsShoppingCart.Models.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace CmsShoppingCart.Controllers
{
    public class PagesController : Controller
    {
        private readonly CmsShoppingCartContext context;
        public PagesController(CmsShoppingCartContext context)
        {
            this.context = context;
        }

        //GET / or /slug
        public async Task<IActionResult> Page(string slug)
        {
            if (slug == null)
            {
                return View(await context.Pages.Where(p => p.Slug == "home").FirstOrDefaultAsync());
            }

            Page page = await context.Pages.Where(p => p.Slug == slug).FirstOrDefaultAsync();

            if (page == null)
            {
                return NotFound();
            }
            return View(page);
        }

    }
}

CmsShoppingCart/Controllers/ProductsController.cs
using CmsShoppingCart.Infrastructure;
using CmsShoppingCart.Models.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace CmsShoppingCart.Controllers
{
    [Authorize]
    public class ProductsController : Controller
    {
        private readonly CmsShoppingCartContext context;

        public ProductsController(CmsShoppingCartContext context)
        {
            this.context = context;
        }
        // GET /products
        public async Task<IActionResult> Index(int p = 1) //you must create a new route take "p" instead "id"
        {
            int pageSize = 6;
            var products = context.Products.OrderByDescending(x => x.Id)
                                            .Skip(( p - 1 ) * pageSize) // if p = 2, this mean the first sex elements are skipped
                                            .Take(pageSize); // return the first 6 elements from the remaining list returned from skip() 

            ViewBag.PageNumber = p;
            ViewBag.PageRange = pageSize;
            ViewBag.TotalPages = (int)Math.Ceiling((decimal)context.Products.Count() / pageSize);

            return View(await products.ToListAsync());
        }

        // GET /products/category
        public async Task<IActionResult> ProductsByCategory(string categorySlug, int p = 1) //you must create a new route take "p" instead "id"
        {
            Category category = await context.Categories.Where(c => c.Slug == categorySlug).FirstOrDefaultAsync();
            if (category == null)
                return RedirectToAction("Index");
            int pageSize = 6;
            var products = context.Products.OrderByDescending(x => x.Id)
                                            .Where(p => p.CategoryId == category.Id)
                                            .Skip(( p - 1 ) * pageSize) // if p = 2, this mean the first sex elements are skipped
                                            .Take(pageSize); // return the first 6 elements from the remaining list returned from skip() 
            ViewBag.CategoryName = category.Name;
            ViewBag.CategorySlug = category.Slug;

            ViewBag.PageNumber = p;
            ViewBag.PageRange = pageSize;

            var productsByCategory = context.Products.OrderByDescending(x => x.Id).Where(p => p.CategoryId == category.Id);

            ViewBag.TotalPages = (int)Math.Ceiling((decimal)productsByCategory.Count() / pageSize);

            return View(await products.ToListAsync());
        }

    }
}

CmsShoppingCart/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Admin Area</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" href="/" >Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Pages" asp-action="Index">Pages</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Categories" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Users" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Roles" asp-action="Index">Roles</a>
                        </li>
                    </ul>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1 justify-content-end">

                        @if (User?.Identity?.IsAuthenticated ?? false)
                        {
                            <li class="nav-item mr-1">
                                <a asp-controller="Account" asp-action="Edit" asp-area="" class="btn btn-primary">
                                    My Account
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-controller="Account" asp-action="Logout" asp-area="" class="btn btn-danger">
                                    Hi, @User.Identity.Name, Logout
                                </a>
                            </li>

                        }
                        else
                        {
                            <li class="nav-item">
                                <a asp-controller="Account" asp-action="Login" class="btn btn-success">Login</a>
                            </li>
                            <li class="nav-item ml-1">
                                <a asp-controller="Account" asp-action="Register" class="btn btn-primary">Register</a>
                            </li>
                        }

                    </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_NotificationPartial" />
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jqueryui/jquery-ui.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/ckeditor/ckeditor.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>